import type { Group, GroupMembershipType } from "./types"

// Helper function to generate slug from name
function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
}

// Helper function to generate random date within last year
function randomDate(start: Date = new Date(Date.now() - 365 * 24 * 60 * 60 * 1000), end: Date = new Date()): string {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString()
}

// Helper function to get random number between min and max
function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

// Generate groups for a specific animal type
export function generateGroupsForAnimal(
  animalType: string,
  categoryId: string,
  count: number = 25,
  startId: number = 1
): Group[] {
  const animalNames: Record<string, string[]> = {
    dog: [
      "Golden Retriever Adventures",
      "Labrador Lovers",
      "Poodle Playdates",
      "German Shepherd Guardians",
      "Bulldog Buddies",
      "Beagle Besties",
      "Rottweiler Runners",
      "Yorkshire Terrier Tales",
      "Dachshund Dreamers",
      "Siberian Husky Hikers",
      "Chihuahua Champions",
      "Border Collie Collectors",
      "Shih Tzu Stories",
      "Great Dane Giants",
      "Boxer Battles",
      "Pomeranian Party",
      "Maltese Memories",
      "French Bulldog Friends",
      "Cocker Spaniel Society",
      "Dalmatian Dots",
      "Saint Bernard Saviors",
      "Australian Shepherd Adventures",
      "Basset Hound Hounds",
      "Weimaraner Warriors",
      "Pug Playground",
      "Boston Terrier Tribe",
      "Doberman Dependables",
      "Schnauzer Squad",
      "Corgi Crew",
      "Jack Russell Jumpers",
    ],
    cat: [
      "Persian Palace",
      "Maine Coon Majesty",
      "Siamese Society",
      "British Shorthair Buddies",
      "Ragdoll Room",
      "Bengal Beauties",
      "Sphynx Circle",
      "Scottish Fold Friends",
      "Abyssinian Adventures",
      "Russian Blue Realm",
      "Norwegian Forest Cats",
      "Oriental Orient",
      "Turkish Angora Alliance",
      "Burmese Buddies",
      "Tonkinese Tribe",
      "Exotic Shorthayrs",
      "American Shorthair Society",
      "Manx Movers",
      "Himalayan Heights",
      "Devon Rex Den",
      "Cornish Rex Crew",
      "Selkirk Rex Squad",
      "LaPerm Lovers",
      "Chartreux Champions",
      "Birman Besties",
      "Bombay Band",
      "Ocicat Owners",
      "Japanese Bobtail Junction",
      "Munchkin Meeting",
      "American Curl Club",
    ],
    bird: [
      "Parrot Paradise",
      "Cockatiel Corner",
      "Canary Caravan",
      "Finch Friends",
      "Budgie Buddies",
      "Lovebird Lovers",
      "Macaw Majesties",
      "African Grey Guardians",
      "Conure Collectors",
      "Amazon Amazons",
      "Cockatoo Crew",
      "Eclectus Enthusiasts",
      "Pionus Pals",
      "Senegal Society",
      "Quaker Quorum",
      "Ringneck Roundup",
      "Parakeet Party",
      "Zebra Finch Zone",
      "Gouldian Finch Friends",
      "Diamond Dove Den",
      "Pigeon Palace",
      "Dove Dreamers",
      "Chicken Keepers",
      "Duck Dynasty",
      "Goose Gatherings",
      "Swan Society",
      "Owl Owners",
      "Hawk Handlers",
      "Eagle Enthusiasts",
      "Falcon Fans",
    ],
    rabbit: [
      "Holland Lop Haven",
      "Netherland Dwarf Network",
      "Flemish Giant Friends",
      "Lionhead Lovers",
      "Angora Alliance",
      "Rex Rabbit Realm",
      "Mini Rex Mix",
      "English Spot Society",
      "French Lop Fans",
      "Dutch Rabbit Den",
      "Mini Lop Meeting",
      "American Rabbit Association",
      "Californian Crew",
      "New Zealand Network",
      "Satin Squad",
      "Silver Fox Friends",
      "Harlequin Hoppers",
      "Jersey Wooly Junction",
      "Polish Rabbit Party",
      "Dwarf Hotot Hub",
      "Belgian Hare Band",
      "English Angora Enthusiasts",
      "French Angora Fans",
      "Giant Angora Group",
      "Cashmere Lop Circle",
      "Thrianta Tribe",
      "Havana Hoppers",
      "Rhinelander Realm",
      "Tan Rabbit Team",
      "Beveren Buddies",
    ],
    hamster: [
      "Syrian Hamster Society",
      "Dwarf Hamster Den",
      "Roborovski Runners",
      "Chinese Hamster Circle",
      "European Hamster Enthusiasts",
      "Campbell Dwarf Collectors",
      "Winter White Warriors",
      "Russian Dwarf Roundup",
      "Long-Haired Hamster Hub",
      "Teddy Bear Hamster Tribe",
      "Golden Hamster Group",
      "Black Bear Hamster Band",
      "Satin Hamster Squad",
      "Albino Hamster Alliance",
      "Cream Hamster Crew",
      "Cinnamon Hamster Circle",
      "Panda Hamster Party",
      "Honey Hamster Haven",
      "Chocolate Hamster Champions",
      "White-Bellied Hamster Hub",
      "Black-Eyed White Hamster",
      "Red-Eyed Hamster Realm",
      "Sable Hamster Society",
      "Pearl Hamster Palace",
      "Umbrous Hamster Union",
      "Umbrous Golden Hamster",
      "Umbrous Yellow Hamster",
      "Umbrous Cream Hamster",
      "Umbrous Cinnamon Hamster",
      "Umbrous Honey Hamster",
    ],
    fish: [
      "Goldfish Guardians",
      "Betta Buddies",
      "Guppy Gang",
      "Angelfish Alliance",
      "Discus Dreamers",
      "Tetra Tribe",
      "Cichlid Circle",
      "Oscar Owners",
      "Koi Keepers",
      "Shark Society",
      "Catfish Crew",
      "Rainbowfish Realm",
      "Molly Meeting",
      "Platy Party",
      "Swordtail Squad",
      "Danio Den",
      "Rasbora Roundup",
      "Barbs Band",
      "Loach Lovers",
      "Pleco Palace",
      "Corydoras Collectors",
      "Ram Cichlid Room",
      "Apistogramma Alliance",
      "Neon Tetra Network",
      "Cardinal Tetra Tribe",
      "Harlequin Rasbora Hub",
      "Zebra Danio Zone",
      "Tiger Barb Team",
      "Cherry Barb Champions",
      "Rosy Barb Roundup",
    ],
    turtle: [
      "Red-Eared Slider Society",
      "Painted Turtle Palace",
      "Box Turtle Buddies",
      "Snapping Turtle Squad",
      "Softshell Turtle Tribe",
      "Map Turtle Meeting",
      "Musk Turtle Musicians",
      "Mud Turtle Masters",
      "Spotted Turtle Society",
      "Diamondback Terrapin Den",
      "Green Sea Turtle Guardians",
      "Hawksbill Turtle Haven",
      "Loggerhead Turtle League",
      "Leatherback Turtle Lovers",
      "Olive Ridley Realm",
      "Kemp's Ridley Keepers",
      "Flatback Turtle Friends",
      "African Side-Neck Network",
      "Asian Box Turtle Alliance",
      "European Pond Turtle Enthusiasts",
      "Yellow-Bellied Slider Squad",
      "Cumberland Slider Circle",
      "River Cooter Crew",
      "Chicken Turtle Champions",
      "Blanding's Turtle Band",
      "Wood Turtle Warriors",
      "Bog Turtle Buddies",
      "Spiny Softshell Society",
      "Florida Softshell Fans",
      "Smooth Softshell Squad",
    ],
    snake: [
      "Ball Python Palace",
      "Corn Snake Circle",
      "King Snake Kingdom",
      "Milk Snake Meeting",
      "Garter Snake Gang",
      "Boa Constrictor Crew",
      "Python Paradise",
      "Anaconda Alliance",
      "Cobra Collectors",
      "Rattlesnake Realm",
      "Copperhead Corner",
      "Cottonmouth Crew",
      "Water Snake Warriors",
      "Rat Snake Roundup",
      "Hognose Snake Hub",
      "Green Tree Python Group",
      "Blood Python Band",
      "Reticulated Python Realm",
      "Burmese Python Buddies",
      "Carpet Python Circle",
      "Boas Band",
      "Rosy Boa Roundup",
      "Sand Boa Society",
      "Kenyan Sand Boa Keepers",
      "Rubber Boa Realm",
      "Rainbow Boa Roundup",
      "Emerald Tree Boa Enthusiasts",
      "Dumeril's Boa Den",
      "Amazon Tree Boa Alliance",
      "Anaconda Adventures",
    ],
    lizard: [
      "Bearded Dragon Den",
      "Leopard Gecko League",
      "Iguana Island",
      "Chameleon Champions",
      "Monitor Lizard Masters",
      "Skink Squad",
      "Anole Alliance",
      "Uromastyx Union",
      "Blue-Tongued Skink Society",
      "Frilled Dragon Friends",
      "Gargoyle Gecko Gang",
      "Crested Gecko Crew",
      "Tokay Gecko Tribe",
      "Day Gecko Dreamers",
      "House Gecko Hub",
      "Fat-Tailed Gecko Fans",
      "African Fat-Tailed Gecko",
      "Knob-Tailed Gecko Keepers",
      "Velvet Gecko Village",
      "Leaf-Tailed Gecko League",
      "Sailfin Dragon Society",
      "Spiny-Tailed Iguana Squad",
      "Green Iguana Guardians",
      "Rhino Iguana Realm",
      "Desert Iguana Den",
      "Collared Lizard Circle",
      "Horned Lizard Haven",
      "Gila Monster Meeting",
      "Komodo Dragon Keepers",
      "Tegu Tribe",
    ],
    "guinea-pig": [
      "Abyssinian Guinea Pig Alliance",
      "Peruvian Guinea Pig Palace",
      "Silkie Guinea Pig Society",
      "Teddy Guinea Pig Tribe",
      "Texel Guinea Pig Team",
      "Coronet Guinea Pig Circle",
      "Crested Guinea Pig Crew",
      "Sheba Guinea Pig Squad",
      "Himalayan Guinea Pig Hub",
      "English Crested Enthusiasts",
      "American Guinea Pig Association",
      "White Guinea Pig Warriors",
      "Tricolor Guinea Pig Troop",
      "Agouti Guinea Pig Alliance",
      "Brindle Guinea Pig Band",
      "Dalmatian Guinea Pig Den",
      "Roan Guinea Pig Realm",
      "Satin Guinea Pig Society",
      "Rex Guinea Pig Roundup",
      "Long-Haired Guinea Pig League",
      "Short-Haired Guinea Pig Squad",
      "Guinea Pig Grooming Group",
      "Guinea Pig Nutrition Network",
      "Guinea Pig Health Hub",
      "Guinea Pig Housing Haven",
      "Guinea Pig Playtime Party",
      "Guinea Pig Show Champions",
      "Guinea Pig Breeding Buddies",
      "Guinea Pig Rescue Roundup",
      "Guinea Pig Care Circle",
    ],
    ferret: [
      "Standard Ferret Society",
      "Angora Ferret Alliance",
      "Albino Ferret Association",
      "Sable Ferret Squad",
      "Chocolate Ferret Circle",
      "Cinnamon Ferret Crew",
      "Champagne Ferret Champions",
      "Dark-Eyed White Den",
      "Blaze Ferret Band",
      "Panda Ferret Palace",
      "Silver Ferret Society",
      "Black Ferret Brigade",
      "White Ferret Warriors",
      "Roan Ferret Realm",
      "Solid Ferret Squad",
      "Ferret Agility Association",
      "Ferret Show Society",
      "Ferret Health Hub",
      "Ferret Nutrition Network",
      "Ferret Enrichment Enthusiasts",
      "Ferret Housing Haven",
      "Ferret Training Tribe",
      "Ferret Grooming Group",
      "Ferret Rescue Roundup",
      "Ferret Breeding Buddies",
      "Ferret Playtime Party",
      "Senior Ferret Support",
      "Baby Ferret Care Circle",
      "Ferret First Aid Friends",
      "Ferret Medical Matters",
    ],
    chinchilla: [
      "Standard Chinchilla Society",
      "Violet Chinchilla Village",
      "White Chinchilla Warriors",
      "Beige Chinchilla Band",
      "Ebony Chinchilla Enthusiasts",
      "Hetero Ebony Hub",
      "Homo Ebony Haven",
      "Tan Chinchilla Tribe",
      "Sapphire Chinchilla Squad",
      "Violet Wrap Society",
      "Blue Diamond Den",
      "Black Velvet Brigade",
      "Brown Velvet Buddies",
      "White Mosaic Masters",
      "Pink White Palace",
      "Chinchilla Care Circle",
      "Chinchilla Nutrition Network",
      "Chinchilla Health Hub",
      "Chinchilla Housing Haven",
      "Chinchilla Dust Bath Den",
      "Chinchilla Enrichment Enthusiasts",
      "Chinchilla Grooming Group",
      "Chinchilla Breeding Buddies",
      "Chinchilla Show Society",
      "Chinchilla Rescue Roundup",
      "Senior Chinchilla Support",
      "Baby Chinchilla Care",
      "Chinchilla First Aid Friends",
      "Chinchilla Medical Matters",
      "Chinchilla Playtime Party",
    ],
    hedgehog: [
      "African Pygmy Hedgehog Alliance",
      "Albino Hedgehog Association",
      "Salt and Pepper Squad",
      "Chocolate Hedgehog Circle",
      "Cinnamon Hedgehog Crew",
      "Pinto Hedgehog Palace",
      "Snowflake Hedgehog Society",
      "Apricot Hedgehog Alliance",
      "Black Hedgehog Band",
      "Gray Hedgehog Gang",
      "White Hedgehog Warriors",
      "Brown Hedgehog Buddies",
      "Hedgehog Care Circle",
      "Hedgehog Nutrition Network",
      "Hedgehog Health Hub",
      "Hedgehog Housing Haven",
      "Hedgehog Enrichment Enthusiasts",
      "Hedgehog Grooming Group",
      "Hedgehog Breeding Buddies",
      "Hedgehog Show Society",
      "Hedgehog Rescue Roundup",
      "Senior Hedgehog Support",
      "Baby Hedgehog Care",
      "Hedgehog First Aid Friends",
      "Hedgehog Medical Matters",
      "Hedgehog Playtime Party",
      "Hedgehog Wheel Warriors",
      "Hedgehog Temperature Tips",
      "Hedgehog Hibernation Help",
      "Hedgehog Quilling Quest",
    ],
    gerbil: [
      "Mongolian Gerbil Meeting",
      "Fat-Tailed Gerbil Friends",
      "Duprasi Gerbil Den",
      "Shaw's Jird Society",
      "Libyan Jird League",
      "Red-Tailed Gerbil Realm",
      "Pallid Gerbil Palace",
      "Naked-Soled Gerbil Network",
      "Great Gerbil Group",
      "Wagner's Gerbil Warriors",
      "Gerbils Galore Gang",
      "Gerbils Unlimited Union",
      "Gerbil Care Circle",
      "Gerbil Nutrition Network",
      "Gerbil Health Hub",
      "Gerbil Housing Haven",
      "Gerbil Enrichment Enthusiasts",
      "Gerbil Grooming Group",
      "Gerbil Breeding Buddies",
      "Gerbil Show Society",
      "Gerbil Rescue Roundup",
      "Senior Gerbil Support",
      "Baby Gerbil Care",
      "Gerbil First Aid Friends",
      "Gerbil Medical Matters",
      "Gerbil Playtime Party",
      "Gerbil Wheel Warriors",
      "Gerbil Burrowing Buddies",
      "Gerbil Sand Bath Squad",
      "Gerbil Digging Den",
    ],
    mouse: [
      "Fancy Mouse Friends",
      "Pet Mouse Palace",
      "House Mouse Haven",
      "Field Mouse Friends",
      "Wood Mouse Warriors",
      "Deer Mouse Den",
      "White Mouse Warriors",
      "Black Mouse Band",
      "Brown Mouse Buddies",
      "Agouti Mouse Alliance",
      "Albino Mouse Association",
      "Chocolate Mouse Circle",
      "Cinnamon Mouse Crew",
      "Lilac Mouse League",
      "Blue Mouse Brigade",
      "Mouse Care Circle",
      "Mouse Nutrition Network",
      "Mouse Health Hub",
      "Mouse Housing Haven",
      "Mouse Enrichment Enthusiasts",
      "Mouse Grooming Group",
      "Mouse Breeding Buddies",
      "Mouse Show Society",
      "Mouse Rescue Roundup",
      "Senior Mouse Support",
      "Baby Mouse Care",
      "Mouse First Aid Friends",
      "Mouse Medical Matters",
      "Mouse Playtime Party",
      "Mouse Wheel Warriors",
    ],
    rat: [
      "Fancy Rat Friends",
      "Pet Rat Palace",
      "Dumbo Rat Den",
      "Rex Rat Realm",
      "Hairless Rat Haven",
      "Manx Rat Meeting",
      "Standard Rat Society",
      "Blue Rat Band",
      "Black Rat Buddies",
      "Agouti Rat Alliance",
      "Albino Rat Association",
      "Chocolate Rat Circle",
      "Cinnamon Rat Crew",
      "Siamese Rat Squad",
      "Himalayan Rat Hub",
      "Rat Care Circle",
      "Rat Nutrition Network",
      "Rat Health Hub",
      "Rat Housing Haven",
      "Rat Enrichment Enthusiasts",
      "Rat Grooming Group",
      "Rat Breeding Buddies",
      "Rat Show Society",
      "Rat Rescue Roundup",
      "Senior Rat Support",
      "Baby Rat Care",
      "Rat First Aid Friends",
      "Rat Medical Matters",
      "Rat Playtime Party",
      "Rat Training Tribe",
    ],
  }

  const groupTypes: Array<"open" | "closed" | "secret"> = ["open", "closed", "open", "open", "closed"]
  const membershipOptions: GroupMembershipType[] = ["open", "request", "invite"]
  const cityBuckets: Record<string, string[]> = {
    dog: ["San Francisco, CA", "Portland, OR", "Denver, CO", "Austin, TX", "Seattle, WA"],
    cat: ["Seattle, WA", "Portland, OR", "Minneapolis, MN", "Chicago, IL", "Boston, MA"],
    bird: ["Austin, TX", "Orlando, FL", "Tampa, FL", "Nashville, TN"],
    rabbit: ["Portland, OR", "Boulder, CO", "Madison, WI", "Asheville, NC"],
    hamster: ["Salt Lake City, UT", "Phoenix, AZ", "Las Vegas, NV"],
    fish: ["Tallahassee, FL", "New Orleans, LA", "Corpus Christi, TX"],
    turtle: ["Jacksonville, FL", "Savannah, GA", "Charleston, SC"],
    snake: ["Phoenix, AZ", "Austin, TX", "Las Vegas, NV"],
    lizard: ["San Diego, CA", "Tucson, AZ", "Orlando, FL"],
    "guinea-pig": ["Pittsburgh, PA", "Columbus, OH", "Cincinnati, OH"],
    ferret: ["Portland, ME", "Burlington, VT", "Albany, NY"],
  }
  const defaultCities = ["New York, NY", "Los Angeles, CA", "Denver, CO", "Chicago, IL", "San Diego, CA", "Seattle, WA"]
  const getCityForAnimal = (type: string, index: number) => {
    const bucket = cityBuckets[type]
    if (bucket?.length) {
      return bucket[index % bucket.length]
    }
    return defaultCities[index % defaultCities.length]
  }
  const createTagline = (description: string) => {
    const normalized = description.replace(/\s+/g, " ").trim()
    return normalized.length > 90 ? `${normalized.slice(0, 90).trim()}…` : normalized
  }
  const descriptions: Record<string, string[]> = {
    dog: [
      "Training tips, meetups, and lifestyle groups for dog people.",
      "Share trail recommendations, swimming spots, and training wins.",
      "Connect with fellow dog owners and share experiences.",
      "Dog care, health, and nutrition discussions.",
      "Outdoor adventures and activities with dogs.",
    ],
    cat: [
      "Indoor enrichment, nutrition, and wellness for cats.",
      "Ideas and support for keeping indoor cats happy and healthy.",
      "Cat behavior, training, and care tips.",
      "Share photos and stories about your feline friends.",
      "Cat health, nutrition, and wellness discussions.",
    ],
    bird: [
      "Parrot care, aviary setups, and training techniques.",
      "From enrichment ideas to training breakthroughs.",
      "Connect with serious bird keepers and enthusiasts.",
      "Bird health, nutrition, and care discussions.",
      "Share your bird's adventures and milestones.",
    ],
    rabbit: [
      "Care tips, housing setups, and nutrition for rabbit owners.",
      "Share your rabbit's daily adventures and care tips.",
      "Rabbit health, nutrition, and wellness discussions.",
      "Connect with fellow rabbit enthusiasts.",
      "Housing, enrichment, and care for happy rabbits.",
    ],
    hamster: [
      "Hamster care, cage setups, and enrichment ideas.",
      "Share your hamster's adventures and care tips.",
      "Hamster health, nutrition, and wellness discussions.",
      "Connect with fellow hamster owners.",
      "Cage setups, enrichment, and care for happy hamsters.",
    ],
    fish: [
      "Aquarium setups, water quality, and fish care.",
      "Share your aquarium setups and fish care tips.",
      "Fish health, nutrition, and wellness discussions.",
      "Connect with fellow aquarium enthusiasts.",
      "Aquarium maintenance, fish care, and breeding tips.",
    ],
    turtle: [
      "Turtle care, habitat setups, and health management.",
      "Share your turtle's habitat and care tips.",
      "Turtle health, nutrition, and wellness discussions.",
      "Connect with fellow turtle owners.",
      "Habitat setups, enrichment, and care for healthy turtles.",
    ],
    snake: [
      "Snake care, enclosure setups, and handling tips.",
      "Share your snake's enclosure and care tips.",
      "Snake health, nutrition, and wellness discussions.",
      "Connect with fellow snake enthusiasts.",
      "Enclosure setups, handling, and care for healthy snakes.",
    ],
    lizard: [
      "Lizard care, terrarium setups, and species-specific advice.",
      "Share your lizard's terrarium and care tips.",
      "Lizard health, nutrition, and wellness discussions.",
      "Connect with fellow lizard owners.",
      "Terrarium setups, enrichment, and care for healthy lizards.",
    ],
    "guinea-pig": [
      "Guinea pig care, cage setups, and nutrition.",
      "Share your guinea pig's adventures and care tips.",
      "Guinea pig health, nutrition, and wellness discussions.",
      "Connect with fellow guinea pig owners.",
      "Cage setups, enrichment, and care for happy guinea pigs.",
    ],
    ferret: [
      "Ferret care, enrichment, and health management.",
      "Share your ferret's adventures and care tips.",
      "Ferret health, nutrition, and wellness discussions.",
      "Connect with fellow ferret owners.",
      "Enrichment, housing, and care for happy ferrets.",
    ],
    chinchilla: [
      "Chinchilla care, cage setups, and dust bath tips.",
      "Share your chinchilla's adventures and care tips.",
      "Chinchilla health, nutrition, and wellness discussions.",
      "Connect with fellow chinchilla owners.",
      "Cage setups, dust baths, and care for healthy chinchillas.",
    ],
    hedgehog: [
      "Hedgehog care, habitat setups, and health tips.",
      "Share your hedgehog's adventures and care tips.",
      "Hedgehog health, nutrition, and wellness discussions.",
      "Connect with fellow hedgehog owners.",
      "Habitat setups, enrichment, and care for happy hedgehogs.",
    ],
    gerbil: [
      "Gerbil care, cage setups, and enrichment ideas.",
      "Share your gerbil's adventures and care tips.",
      "Gerbil health, nutrition, and wellness discussions.",
      "Connect with fellow gerbil owners.",
      "Cage setups, enrichment, and care for happy gerbils.",
    ],
    mouse: [
      "Mouse care, cage setups, and health management.",
      "Share your mouse's adventures and care tips.",
      "Mouse health, nutrition, and wellness discussions.",
      "Connect with fellow mouse owners.",
      "Cage setups, enrichment, and care for healthy mice.",
    ],
    rat: [
      "Rat care, cage setups, and training tips.",
      "Share your rat's adventures and care tips.",
      "Rat health, nutrition, and wellness discussions.",
      "Connect with fellow rat owners.",
      "Cage setups, enrichment, and care for happy rats.",
    ],
  }

  const tags: Record<string, string[]> = {
    dog: ["dogs", "training", "health", "nutrition", "adventures", "meetups"],
    cat: ["cats", "enrichment", "health", "nutrition", "indoor", "wellness"],
    bird: ["birds", "training", "health", "care", "aviary", "enrichment"],
    rabbit: ["rabbits", "care", "housing", "nutrition", "health", "enrichment"],
    hamster: ["hamsters", "care", "cage", "enrichment", "health", "nutrition"],
    fish: ["fish", "aquarium", "care", "water-quality", "health", "breeding"],
    turtle: ["turtles", "habitat", "care", "health", "nutrition", "enrichment"],
    snake: ["snakes", "enclosure", "care", "handling", "health", "nutrition"],
    lizard: ["lizards", "terrarium", "care", "health", "nutrition", "enrichment"],
    "guinea-pig": ["guinea-pigs", "care", "cage", "nutrition", "health", "enrichment"],
    ferret: ["ferrets", "care", "enrichment", "health", "nutrition", "housing"],
    chinchilla: ["chinchillas", "care", "cage", "dust-bath", "health", "nutrition"],
    hedgehog: ["hedgehogs", "care", "habitat", "health", "nutrition", "enrichment"],
    gerbil: ["gerbils", "care", "cage", "enrichment", "health", "nutrition"],
    mouse: ["mice", "care", "cage", "health", "nutrition", "enrichment"],
    rat: ["rats", "care", "cage", "training", "health", "nutrition"],
  }

  const groups: Group[] = []
  const names = animalNames[animalType] || []
  const descs = descriptions[animalType] || ["A community for pet owners."]
  const animalTags = tags[animalType] || [animalType]

  for (let i = 0; i < count; i++) {
    const name = names[i % names.length] || `${animalType.charAt(0).toUpperCase() + animalType.slice(1)} Group ${i + 1}`
    const slug = generateSlug(name)
    const type = groupTypes[i % groupTypes.length]
    const description = descs[i % descs.length]
    const memberCount = randomInt(5, 500)
    const topicCount = randomInt(0, 50)
    const postCount = randomInt(0, 200)
    const createdAt = randomDate()
    const updatedAt = randomDate(new Date(createdAt), new Date())
    const ownerId = randomInt(1, 10).toString()
    const membershipType = membershipOptions[(startId + i) % membershipOptions.length]
    const tagline = createTagline(description)
    const city = getCityForAnimal(animalType, i)
    const isVerified = (startId + i) % 7 === 0

    // Generate cover image URL - using placeholder service
    const coverImage = `https://picsum.photos/seed/${animalType}-${i}-cover/800/400`
    const avatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${Math.floor(Math.random() * 16777215).toString(16)}&color=fff&size=128`

    groups.push({
      id: `group-${animalType}-${startId + i}`,
      name,
      slug: `${slug}-${startId + i}`,
      description,
      type,
      categoryId,
      ownerId,
      coverImage,
      avatar,
      memberCount,
      topicCount,
      postCount,
      tags: [animalTags[0], animalTags[1], animalTags[2]],
      rules: ["Be kind and respectful", "No sales posts", "Share helpful advice"],
      pinnedRules: ["Keep discussions constructive", "Share sources for advice"],
      membershipType,
      city,
      tagline,
      isVerified,
      moderators: [ownerId],
      createdAt,
      updatedAt,
      visibility: {
        discoverable: type !== "secret",
        content: type === "open" ? "everyone" : "members",
      },
    })
  }

  return groups
}
