import type { BlogPost, BlogPostMedia } from "./types"
import { addBlogPost, getBlogPosts, getPets, getUsers } from "./storage"

/**
 * Seeds 20 blog posts with diverse content
 */
export function seedBlogPosts() {
  if (typeof window === "undefined") return

  const existingPosts = getBlogPosts()
  const pets = getPets()
  const users = getUsers()

  if (pets.length === 0 || users.length === 0) {
    console.warn("Cannot seed blog posts: No pets or users found")
    return
  }

  // Generate 20 unique post IDs starting from timestamp
  const baseId = Date.now()
  const seedPosts: BlogPost[] = [
    {
      id: `${baseId}-1`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Our First Day Together: A Journey Begins",
      content: "Today marks a special milestone - it's been exactly one year since we welcomed our furry friend into our family. From the nervous first day to the confident companion we have today, every moment has been a blessing.\n\nWe started with basic training, lots of patience, and endless love. Now we're inseparable! The transformation has been incredible to witness.",
      coverImage: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1280&h=720&fit=crop",
      tags: ["adoption", "anniversary", "milestone", "family"],
      categories: ["Care"],
      hashtags: ["petlove", "adoptionstory", "furbaby"],
      media: {
        images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1280&h=720&fit=crop"],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-2`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Training Success: Sit, Stay, Come - Mastered!",
      content: "After weeks of consistent training, we've finally mastered the three essential commands! The breakthrough moment was when I realized that short, frequent sessions work much better than long ones.\n\n**Key Tips:**\n- Keep sessions to 5-10 minutes\n- Use high-value treats\n- End on a positive note\n- Practice in different environments\n\nPersistence pays off!",
      tags: ["training", "obedience", "commands", "tips"],
      categories: ["Training"],
      hashtags: ["dogtraining", "puppytraining", "obedience"],
      media: {
        images: ["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=1280&h=720&fit=crop"],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-3`,
      petId: pets[2]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[2]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Beach Adventure: Sand, Waves, and Pure Joy",
      content: "First beach trip was an absolute success! The excitement was palpable from the moment we arrived. Running on the sand, chasing waves, meeting other dogs - it was a perfect day.\n\nThe beach offers so much enrichment:\n- Natural exercise\n- Socialization opportunities\n- Mental stimulation\n- Bonding time\n\nWe'll definitely be back next weekend!",
      coverImage: "https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=1280&h=720&fit=crop",
      tags: ["beach", "adventure", "outdoor", "exercise"],
      categories: ["Adventure"],
      hashtags: ["beachday", "dogadventure", "outdoorfun"],
      media: {
        images: [
          "https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=1280&h=720&fit=crop",
          "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=1280&h=720&fit=crop",
        ],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-4`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Homemade Treat Recipes: 5 Easy Favorites",
      content: "Sharing my top 5 homemade treat recipes that are healthy, affordable, and easy to make!\n\n**1. Peanut Butter Bites**\n- 1 cup whole wheat flour\n- 1/2 cup peanut butter (xylitol-free)\n- 1/4 cup water\n- Mix, roll, cut, bake at 350°F for 15 minutes\n\n**2. Frozen Yogurt Drops**\n- Plain Greek yogurt\n- Mix with mashed banana\n- Freeze in ice cube tray\n\n**3. Sweet Potato Chews**\n- Slice sweet potato\n- Bake at 250°F for 2-3 hours\n- Cool completely\n\n**4. Apple Carrot Cookies**\n- Grated apple and carrot\n- Oat flour\n- Coconut oil\n- Bake until golden\n\n**5. Chicken Jerky**\n- Thin-sliced chicken breast\n- Dehydrate at 165°F for 6-8 hours\n\nAll recipes are vet-approved and use simple, wholesome ingredients!",
      tags: ["recipes", "treats", "nutrition", "homemade", "cooking"],
      categories: ["Care"],
      hashtags: ["homemadetreats", "dogrecipes", "healthytreats"],
      media: {
        images: ["https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=1280&h=720&fit=crop"],
        videos: [],
        links: [
          {
            url: "https://www.akc.org/expert-advice/nutrition/homemade-dog-treats/",
            title: "AKC Guide to Homemade Dog Treats",
          },
        ],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-5`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Vet Visit Success: Annual Checkup Results",
      content: "Annual checkup completed and everything looks great! The vet was impressed with our health maintenance routine.\n\n**Checkup Summary:**\n- ✅ All vaccinations up to date\n- ✅ Healthy weight maintained\n- ✅ Clean teeth (dental care working!)\n- ✅ Perfect heart and lung sounds\n- ✅ Shiny coat (nutrition on point)\n\n**Maintenance Tips Shared:**\n1. Continue daily brushing\n2. Keep up with monthly preventatives\n3. Maintain current exercise routine\n4. Annual blood work scheduled\n\nPreventive care is the best care!",
      tags: ["health", "vet", "checkup", "wellness", "care"],
      categories: ["Care"],
      hashtags: ["vetvisit", "pethealth", "wellness"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-6`,
      petId: pets[2]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[2]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Agility Training: Our First Competition",
      content: "Took the plunge and entered our first agility competition! While we didn't place, we had an absolute blast and learned so much.\n\nThe course was challenging but fair:\n- Weave poles (our weak point)\n- A-frame (nailed it!)\n- Tunnel (favorite obstacle)\n- Jump sequence (needs practice)\n\n**What We Learned:**\n- Competition environment is different from practice\n- Focus on having fun, not winning\n- There's always room for improvement\n- The community is incredibly supportive\n\nNext competition is in 3 months. Time to train!",
      tags: ["agility", "competition", "training", "sports"],
      categories: ["Training"],
      hashtags: ["agilitytraining", "dogcompetition", "sports"],
      media: {
        images: ["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=1280&h=720&fit=crop"],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-7`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Seasonal Safety: Winter Care Essentials",
      content: "Winter is here, and it's time to adjust our care routine! Here's what we're doing to keep our pet safe and comfortable during the colder months:\n\n**Paw Protection:**\n- Using pet-safe ice melt\n- Wiping paws after walks\n- Checking for cracks or irritation\n- Applying paw balm when needed\n\n**Indoor Comfort:**\n- Extra cozy bedding\n- Staying warm but not overheating\n- Maintaining humidity levels\n\n**Nutrition:**\n- Slightly adjusted portions (less outdoor activity)\n- Ensuring access to fresh water\n- Watching for weight changes\n\nStay warm and safe this winter!",
      tags: ["winter", "safety", "seasonal", "care", "wellness"],
      categories: ["Care"],
      hashtags: ["wintercare", "petsafety", "seasonal"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-8`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Socialization Success: Meeting New Friends",
      content: "Today's playdate was a huge success! Meeting new dogs can be challenging, but with proper introduction and patience, it went perfectly.\n\n**Introduction Process:**\n1. Neutral territory (local park)\n2. Parallel walking at distance\n3. Gradual approach\n4. Off-leash play in fenced area\n5. Positive reinforcement throughout\n\n**What Worked:**\n- Starting with calm, well-socialized dogs\n- Reading body language carefully\n- Keeping first meeting short\n- Ending on a positive note\n\nSocialization is an ongoing process, and every successful interaction builds confidence!",
      tags: ["socialization", "playdate", "behavior", "training"],
      categories: ["Training"],
      hashtags: ["socialization", "dogfriends", "playdate"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-9`,
      petId: pets[2]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[2]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Hiking Adventures: Trail Safety Tips",
      content: "Love hiking with our adventure buddy? Here are essential safety tips we've learned from years on the trails:\n\n**Pre-Hike Preparation:**\n- Check trail conditions and weather\n- Pack sufficient water for both of you\n- Bring first aid kit (human and pet)\n- Know your route and difficulty level\n- Check for trail restrictions\n\n**On the Trail:**\n- Keep on leash unless in designated off-leash areas\n- Watch for wildlife encounters\n- Take regular breaks\n- Monitor for overheating signs\n- Leave no trace\n\n**Post-Hike:**\n- Check for ticks\n- Inspect paws for injuries\n- Provide fresh water and rest\n- Reward good behavior!\n\nSafety first means more adventures together!",
      coverImage: "https://images.unsplash.com/photo-1502904550040-7534597429ae?w=1280&h=720&fit=crop",
      tags: ["hiking", "outdoor", "safety", "adventure", "trails"],
      categories: ["Adventure"],
      hashtags: ["hikingwithdogs", "trailsafety", "outdooradventure"],
      media: {
        images: ["https://images.unsplash.com/photo-1502904550040-7534597429ae?w=1280&h=720&fit=crop"],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-10`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Funny Moments: When Zoomies Take Over",
      content: "Caught the most hilarious zoomie session on camera today! It started with a simple squeaky toy and escalated into a full apartment tour at maximum speed.\n\n**The Sequence:**\n1. Toy squeaked\n2. Ears perked up\n3. Tail started wagging\n4. Full zoomie mode activated\n5. 5-minute lap around the house\n6. Collapsed in exhaustion\n\nThese moments of pure joy are why we love having pets. The unpredictable, goofy, and absolutely endearing behaviors never fail to bring a smile.\n\nWhat's your pet's funniest zoomie story?",
      tags: ["funny", "zoomies", "entertainment", "videos"],
      categories: ["Funny"],
      hashtags: ["zoomies", "funnydogs", "petvideos"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-11`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Grooming Routine: Tips for Stress-Free Baths",
      content: "Bath time used to be a struggle, but we've perfected our routine! Here's what works for us:\n\n**Preparation is Key:**\n- Gather all supplies first\n- Use lukewarm water\n- Choose pet-safe shampoo\n- Have towels ready\n- Treats for positive reinforcement\n\n**During the Bath:**\n- Start with calm, soothing voice\n- Use gentle massage motions\n- Avoid face area initially\n- Take breaks if needed\n- Reward calm behavior\n\n**After the Bath:**\n- Thorough but gentle drying\n- Reward with favorite treat\n- Extra cuddle time\n- Keep warm until fully dry\n\nRegular grooming keeps them healthy and strengthens your bond!",
      tags: ["grooming", "bath", "care", "tips", "routine"],
      categories: ["Care"],
      hashtags: ["grooming", "bathtime", "petcare"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-12`,
      petId: pets[2]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[2]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Photography Tips: Capturing Perfect Pet Photos",
      content: "As an amateur pet photographer, I've learned a few tricks for getting those perfect shots:\n\n**Lighting:**\n- Natural light is your friend\n- Avoid harsh midday sun\n- Golden hour produces warm tones\n- Use windows for indoor shots\n\n**Composition:**\n- Get on their level\n- Use leading lines\n- Capture action and stillness\n- Focus on the eyes\n\n**Patience:**\n- Let them be natural\n- Use toys or treats for attention\n- Take many shots\n- The best photos happen spontaneously\n\n**Equipment:**\n- Phone camera works great!\n- Use portrait mode for depth\n- Burst mode for action shots\n- Edit lightly, preserve authenticity\n\nShare your best pet photos!",
      coverImage: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=1280&h=720&fit=crop",
      tags: ["photography", "photos", "tips", "creativity"],
      categories: ["Photos"],
      hashtags: ["petphotography", "phototips", "petpics"],
      media: {
        images: [
          "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=1280&h=720&fit=crop",
          "https://images.unsplash.com/photo-1552053831-71594a27632d?w=1280&h=720&fit=crop",
        ],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-13`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Behavioral Training: Overcoming Separation Anxiety",
      content: "Separation anxiety is challenging, but we're making great progress! Here's our journey and what's working:\n\n**Signs We Noticed:**\n- Destructive behavior when alone\n- Excessive barking/whining\n- Pacing and restlessness\n- Loss of appetite\n\n**Strategies We're Using:**\n1. Gradual desensitization\n2. Create positive associations with departures\n3. Interactive toys for mental stimulation\n4. Calm departure and arrival routines\n5. Professional guidance when needed\n\n**Progress So Far:**\n- Can be alone for 30 minutes\n- Reduced destructive behavior\n- More relaxed during departures\n\nEvery small step is a victory. Patience and consistency are key!",
      tags: ["behavior", "anxiety", "training", "wellness"],
      categories: ["Training"],
      hashtags: ["separationanxiety", "behaviortraining", "petwellness"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-14`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Nutrition Guide: Understanding Pet Food Labels",
      content: "Reading pet food labels can be confusing! Here's a simple breakdown:\n\n**Key Ingredients:**\n- Look for named protein sources first\n- Whole grains vs. by-products\n- Avoid artificial colors/flavors\n- Natural preservatives preferred\n\n**Nutritional Info:**\n- AAFCO statement (complete & balanced)\n- Life stage appropriate\n- Protein percentage\n- Fat content for your pet's needs\n\n**What to Avoid:**\n- Unspecified meat sources\n- Excessive fillers\n- Artificial additives\n- Recalled brands\n\n**Our Approach:**\n- Consult with vet\n- Read ingredients carefully\n- Monitor weight and health\n- Adjust as needed\n\nKnowledge is power when it comes to nutrition!",
      tags: ["nutrition", "food", "health", "diet", "wellness"],
      categories: ["Care"],
      hashtags: ["petnutrition", "healthyeating", "petfood"],
      media: {
        images: [],
        videos: [],
        links: [
          {
            url: "https://www.fda.gov/animal-veterinary/animal-food-feeds/pet-food",
            title: "FDA Pet Food Information",
          },
        ],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-15`,
      petId: pets[2]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[2]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Playtime Ideas: Interactive Toys That Work",
      content: "Keeping pets mentally and physically stimulated is crucial. Here are our favorite interactive toys:\n\n**Puzzle Feeders:**\n- Slow down eating\n- Mental enrichment\n- Variety of difficulty levels\n- Easy to clean\n\n**Fetch Toys:**\n- Classic frisbee (durable)\n- Tennis balls (safe versions)\n- Rope toys for tug\n- Floating toys for water play\n\n**Interactive Puzzles:**\n- Treat-dispensing toys\n- Hide and seek games\n- Snuffle mats\n- Learning new tricks\n\n**DIY Options:**\n- Cardboard box maze\n- Frozen treat toys\n- Scatter feeding\n- Obstacle courses\n\nRotate toys to maintain interest. What are your pet's favorites?",
      tags: ["toys", "playtime", "enrichment", "exercise"],
      categories: ["Playtime"],
      hashtags: ["interactivetoys", "playtime", "petenrichment"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-16`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Travel Tips: Road Tripping with Pets",
      content: "Planning a road trip? Here's how we make travel safe and enjoyable for everyone:\n\n**Pre-Trip Prep:**\n- Update ID tags and microchip\n- Health certificate if needed\n- Pack familiar items (bedding, toys)\n- First aid kit\n- Current photos (just in case)\n\n**On the Road:**\n- Regular rest stops every 2-3 hours\n- Never leave alone in car\n- Secure in carrier or harness\n- Keep hydrated\n- Monitor for stress signs\n\n**At Destination:**\n- Pet-friendly accommodations confirmed\n- Maintain routine as much as possible\n- Supervise in new environments\n- Emergency vet info handy\n\nSafe travels! Adventure awaits!",
      coverImage: "https://images.unsplash.com/photo-1502810365585-56caf9b9c8cb?w=1280&h=720&fit=crop",
      tags: ["travel", "roadtrip", "safety", "adventure"],
      categories: ["Adventure"],
      hashtags: ["petravel", "roadtrip", "travelwithpets"],
      media: {
        images: ["https://images.unsplash.com/photo-1502810365585-56caf9b9c8cb?w=1280&h=720&fit=crop"],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-17`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Adoption Story: Finding Our Perfect Match",
      content: "Two years ago today, we walked into the shelter \"just to look\" and walked out with our best friend. Here's our story:\n\n**The Search:**\nWe visited several shelters, looking for a companion that would fit our lifestyle. We weren't in a rush and wanted to find the right match.\n\n**The Meeting:**\nIt was love at first sight. The connection was immediate - calm, gentle, and curious. We spent time in the play area and knew this was it.\n\n**The Adjustment:**\nFirst few weeks required patience:\n- New environment adjustment\n- Establishing routines\n- Building trust\n- Learning each other's cues\n\n**Today:**\nTwo years later, I can't imagine life without this amazing companion. Every day brings new joys, challenges, and love.\n\nIf you're considering adoption, visit your local shelter. Your perfect match might be waiting!",
      tags: ["adoption", "shelter", "story", "love"],
      categories: ["Care"],
      hashtags: ["adoptionstory", "rescuedog", "adoptdontshop"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-18`,
      petId: pets[2]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[2]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Health Awareness: Recognizing Emergency Signs",
      content: "Knowing when to seek emergency veterinary care can save lives. Here are critical signs to watch for:\n\n**Immediate Emergency Signs:**\n- Difficulty breathing\n- Unconsciousness or collapse\n- Severe injury or trauma\n- Seizures (especially first-time)\n- Ingestion of toxic substances\n- Severe vomiting/diarrhea with lethargy\n- Unable to urinate\n\n**Urgent (Call Vet):**\n- Persistent vomiting/diarrhea\n- Loss of appetite for 24+ hours\n- Lethargy and weakness\n- Swollen abdomen\n- Eye injuries\n- Heatstroke symptoms\n\n**Preparation:**\n- Emergency vet contact info saved\n- Know location of 24/7 clinic\n- Keep medical records accessible\n- Pet insurance information ready\n\n**When in Doubt:**\nAlways err on the side of caution. If you're worried, call your vet. Better safe than sorry!\n\nStay informed, stay prepared!",
      tags: ["health", "emergency", "safety", "wellness", "veterinary"],
      categories: ["Care"],
      hashtags: ["petemergency", "pethealth", "vetsafety"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-19`,
      petId: pets[0]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[0]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Community Spotlight: Local Dog Park Adventures",
      content: "Our local dog park has become our second home! Here's why we love it:\n\n**The Community:**\nAmazing group of regulars who've become like family. We look out for each other's pets and share tips, stories, and laughs.\n\n**The Space:**\n- Large fenced areas for different sizes\n- Separate puppy area\n- Water stations\n- Shaded seating\n- Walking trails nearby\n\n**The Benefits:**\n- Socialization opportunities\n- Exercise for both of us\n- Mental stimulation\n- Routine establishment\n- Weather-permitting fun\n\n**Etiquette We Follow:**\n- Always pick up after ourselves\n- Respect space and signals\n- Supervise at all times\n- Leave if behavior becomes concerning\n- Share, don't hoard toys\n\nDog parks aren't for every pet, but when they work, they're wonderful!",
      tags: ["community", "dogpark", "socialization", "local"],
      categories: ["Adventure"],
      hashtags: ["dogpark", "community", "localadventure"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
    {
      id: `${baseId}-20`,
      petId: pets[1]?.id || pets[Math.floor(Math.random() * pets.length)].id,
      authorId: users[1]?.id || users[Math.floor(Math.random() * users.length)].id,
      title: "Reflection: What My Pet Has Taught Me",
      content: "As we celebrate another year together, I've been reflecting on the profound lessons my pet has taught me:\n\n**Living in the Moment:**\nPets don't worry about yesterday or tomorrow. They're fully present, and that's a beautiful reminder to enjoy the now.\n\n**Unconditional Love:**\nThe pure, unwavering love our pets give us is humbling and inspiring. It reminds us to love more openly.\n\n**Patience:**\nTraining and care require patience. This has made me more patient in all areas of life.\n\n**Responsibility:**\nCaring for another being teaches responsibility in a deeply meaningful way.\n\n**Joy in Simple Things:**\nA walk, a treat, a belly rub - pure joy in life's simple pleasures.\n\n**Communication:**\nLearning to read subtle cues and body language has improved all my relationships.\n\n**Resilience:**\nWatching pets bounce back from challenges inspires resilience.\n\n**Gratitude:**\nEvery day with them is a gift worth appreciating.\n\nWhat has your pet taught you?",
      tags: ["reflection", "gratitude", "life", "love", "wisdom"],
      categories: ["Care"],
      hashtags: ["petlove", "reflection", "gratitude"],
      media: {
        images: [],
        videos: [],
        links: [],
      },
      likes: [],
      reactions: {
        like: [],
        love: [],
        laugh: [],
        wow: [],
        sad: [],
        angry: [],
      },
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      privacy: "public",
      isDraft: false,
    },
  ]

  // Check if posts already exist to avoid duplicates
  const existingIds = new Set(existingPosts.map((p) => p.id))
  const newPosts = seedPosts.filter((post) => !existingIds.has(post.id))

  if (newPosts.length === 0) {
    console.log("All 20 blog posts already seeded")
    return
  }

  // Add new posts to storage
  newPosts.forEach((post) => {
    addBlogPost(post)
  })

  console.log(`Seeded ${newPosts.length} new blog posts`)
}

